Bump version to 3.10.0.0
criteo/android-publisher-sdk-mopub-adapters pull request #25
Opened 2020-08-26 16:52 UTC by Amokrane

2020-08-26 16:53 UTC, TurpIF requested changes
CHANGELOG.md ?

2020-08-27 09:39 UTC, Amokrane commented
@TurpIF  Can you double check if the headers are in the right format? (Used `Version xxx`)

2020-08-27 10:29 UTC, TurpIF commented
> @TurpIF Can you double check whether the headers are in the right format? (Used `Version xxx`)

There is no generated changelog nor Slack message from this. So no expected structure on this :)

2020-08-27 10:29 UTC, TurpIF approved these changes

2020-08-27 10:38 UTC, merged